site_name: FoxxAI Research Journal
site_url: https://foxxai.xyz

theme:
  name: material
  logo: assets/avatar.png
  favicon: assets/avatar.png
  font:
    text: false
    code: false
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.prune
    - navigation.instant
    - header.autohide
    - toc.integrate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags
