site_name: FoxxAI Research Journal
site_url: https://foxxai.xyz

theme:
  name: material
  logo: assets/avatar.png
  favicon: assets/avatar.png
  font:
    text: false
    code: false
  icon:
    logo: null
  footer:
    social: false
    generator: false  # This should disable the "Made with" text
extra:
  generator: false    # Belt and suspenders approach to disable generator notice
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.prune
    - navigation.instant
    - header.autohide
    - toc.integrate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags

copyright: All content copyright by the author (2025). Comments and feedback are welcome at 546f6464.jbb@gmail.com.
