site_name: FoxxAI Research Journal
site_url: https://foxxai.xyz

theme:
  name: material
  logo: assets/avatar.png
  favicon: assets/avatar.png
  font:
    text: false
    code: false
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.prune
    - navigation.instant
    - header.autohide
    - toc.integrate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags
