site_name: "Human-LLM Interaction as Functionalist Activity: Reconfiguring Techno-cultural Praxis"
site_url: https://foxxai.xyz
use_directory_urls: false

theme:
  name: material
  logo: assets/avatar.png
  favicon: assets/avatar.png
  font:
    text: false
    code: false
  icon:
    logo: null
  footer:
    social: false
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.prune
    - navigation.instant
    - header.autohide
    - toc.integrate

extra_css:
  - stylesheets/extra.css
  - stylesheets/gallery.css

extra_javascript:
  - javascripts/gallery.js

plugins:
  - search
  - tags

nav:
  - Home: index.md
  - Research Blog:
      - Overview: entries/index.md
      - Articles:
          - A Highly Reduced OmniGen Installation Experience: entries/2025-01-19.md
  - Select Publications: publications/index.md
  - Academic Travelogue: travelogue/index.md
  - Associates & Associations: associates/index.md

markdown_extensions:
  - md_in_html
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - abbr

copyright: All content copyright by the author (2025). Comments and feedback are welcome at 546f6464.jbb@gmail.com.
