name: Deploy MkDocs site
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/configure-pages@v3
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build site
        run: mkdocs build

      # Update this section
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4  # Changed from v3 to v4
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}